const IMAGES = [
  [
    {
      title: 'haerin',
      url: 'haerin.jpg',
      text: 'abstracted face of haerin',
      medium: 'charcoal',
      date: '12/05/23',
      pos: 2,
      idx: 0,
    },
    {
      title: 'dancer',
      url: 'dancer.jpg',
      text: 'figure of IU dancing',
      medium: 'charcoal',
      date: '12/07/23',
      pos: 4,
      idx: 1,
    },
  ],
  [
    {
      title: 'sleepy',
      url: 'sleepy.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'charcoal',
      date: '11/16/23',
      pos: 3,
      idx: 2,
    },
  ],
  [
    {
      title: 'vaporwave',
      url: '3.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'shot on canon ae-1',
      date: '11/12/23',
      pos: 5,
      idx: 3,
    },
    {
      title: 'dichotomy',
      url: 'dichotomy.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'charcoal',
      date: '11/16/23',
      pos: 6,
      idx: 4,
    },
    {
      title: 'chillin',
      url: 'chillin.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'charcoal',
      date: '11/16/23',
      pos: 8,
      idx: 5,
    },
  ],
  [
    {
      title: 'gold',
      url: '4.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'shot on canon ae-1',
      date: '11/12/23',
      pos: 7,
      idx: 6,
    },
  ],
  [
    {
      title: 'bag',
      url: '7.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'shot on canon ae-1',
      date: '11/12/23',
      pos: 3,
      idx: 7,
    },
    {
      title: 'nova',
      url: '8.jpg',
      text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque possimus blanditiis ut eveniet. Libero nesciunt delectus provident quisquam facere aut inventore perferendis repellat eveniet nobis maxime illo, quam natus. Minima eaque eius itaque repudiandae sequi. Fuga sit vitae voluptatum? Excepturi nostrum modi labore ipsum quo porro ad minus quam similique?',
      medium: 'shot on canon ae-1',
      date: '11/12/23',
      pos: 5,
      idx: 8,
    },
  ],
]

export { IMAGES }
